"""
Aggregate per-section JSON summaries into a single presentation_data.json
containing the headline numbers required for slides.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from markov_chain.common import (  # noqa: E402
    DATA_DIR,
    REPO_ROOT,
    load_notes,
    load_state_order,
)


def load_json(name: str) -> dict:
    with (DATA_DIR / name).open() as f:
        return json.load(f)


def main() -> None:
    states = load_state_order()
    df = load_notes()

    # Per-section summaries (generated by sections 1-9)
    s1 = load_json("section1_summary.json")
    s2 = load_json("section2_summary.json")
    s3 = load_json("section3_summary.json")
    s4 = load_json("section4_summary.json")
    s5 = load_json("section5_summary.json")
    s6 = load_json("section6_summary.json")
    s7 = load_json("section7_summary.json")
    s9 = load_json("section9_summary.json")

    # Resolve s1 entries (they were saved as a list)
    s1_by_name = {row["operator"]: row for row in s1}

    # Find the V7 -> I cell in section-5 output for explicit reporting
    v7_cells = {f"{row['source']} -> {row['target']}": row for row in s5["v7_to_I_cells"]}

    headline = {
        "corpus": {
            "tunes": int(df["tune_id"].nunique()),
            "total_notes": int(len(df)),
            "states_observed": int(len(states)),
            "states_theoretical": 325,  # 12 SD * 5 quality * 5 beat (notes) + 1 REST * 5 quality * 5 beat
            "on_beat_fraction": float((df["beat_position"] == "on").mean()),
            "chord_change_rate": float(df["chord_changed_from_prev"].mean()),
            "quality_distribution": {q: int((df["chord_quality"] == q).sum())
                                     for q in df["chord_quality"].unique()},
        },
        "transitions": {
            "total_all":    int(s1_by_name["P (all transitions)"]["total_transitions"]),
            "total_within": int(s1_by_name["P_within"]["total_transitions"]),
            "total_across": int(s1_by_name["P_across"]["total_transitions"]),
            "sparsity_pct": {
                "P":         float(s1_by_name["P (all transitions)"]["sparsity_pct"]),
                "P_within":  float(s1_by_name["P_within"]["sparsity_pct"]),
                "P_across":  float(s1_by_name["P_across"]["sparsity_pct"]),
            },
        },
        "stationary": {
            name: {
                "pearson_r_vs_empirical": s2[name]["pearson_r_vs_empirical"],
                "top_3": s2[name]["top_10"][:3],
            }
            for name in ("P", "P_within", "P_across")
        },
        "spectral": {
            name: {
                "lambda_2_abs": s3[name]["lambda_2"]["abs"],
                "spectral_gap": s3[name]["spectral_gap"],
                "mixing_time_steps": s3[name]["mixing_time_steps"],
            }
            for name in ("P", "P_within", "P_across")
        },
        "hitting_times": {
            name: {
                "median": s4[name]["h_median"],
                "min": s4[name]["h_min"],
                "max": s4[name]["h_max"],
                "shortest_3": s4[name]["shortest_8"][:3],
            }
            for name in ("P", "P_within", "P_across")
        },
        "voice_leading_top_10_P_across": s5["P_across_top_20"][:10],
        "v7_to_I_cells": v7_cells,
        "null_comparison": {
            name: {
                "chi2_observed":      s6[name]["chi2_observed"],
                "chi2_null_mean":     s6[name]["chi2_null_mean"],
                "chi2_p_value":       s6[name]["chi2_p_value"],
                "kl_observed":        s6[name]["kl_observed"],
                "kl_null_mean":       s6[name]["kl_null_mean"],
                "kl_p_value":         s6[name]["kl_p_value"],
                "permutations":       s6[name]["permutations"],
            }
            for name in ("P", "P_within", "P_across")
        },
        "memory_order": {
            name: {
                "delta_BIC_obs":      s7[name]["delta_BIC_obs"],
                "delta_AIC_obs":      s7[name]["delta_AIC_obs"],
                "test_mean_ll_order1": s7[name]["test_mean_ll_order1"],
                "test_mean_ll_order2": s7[name]["test_mean_ll_order2"],
                "test_mean_ll_delta":  s7[name]["test_mean_ll_delta"],
            }
            for name in ("P", "P_within", "P_across")
        },
        "generative_validation": {
            "M_trajectories": s9["M_trajectories"],
            "T_length":       s9["T_length"],
            "pearson_r_f_sim_vs_pi":     s9["pearson_r_f_sim_vs_pi"],
            "total_variation_f_sim_vs_pi": s9["total_variation_f_sim_vs_pi"],
        },
    }

    out_path = REPO_ROOT / "markov_chain" / "presentation_data.json"
    with out_path.open("w") as f:
        json.dump(headline, f, indent=2)
    print(f"Wrote {out_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
